[camera1]
fov_x = 0.3
fov_y = 0.3
pos_x = 0
pos_y = 0
pos_z = 0
pitch = 0
yaw = -0.3
roll = 0

[camera2]
fov_x = 0.3
fov_y = 0.3
pos_x = 3
pos_y = 3
pos_z = 3
pitch = -0.2
yaw = 0.3
roll = 0

[[devices]]
name = "Fist of Family Values"
min_x = -69
min_y = -69
min_z = -69
max_x = -37
max_y = -37
max_z = -37

[[devices]]
name = "Distributor of Freedom"
min_x = 0
min_y = 0
min_z = 0
max_x = 37
max_y = 37
max_z = 37
