[camera1]
fov_x = 0.93337511
fov_y = 0.72274084
pos_x = 0
pos_y = 0
pos_z = 0
pitch = 0
yaw = 0
roll = 0
img_height = 972
img_width = 1296

[camera2]
fov_x = 0.8796459
fov_y = 0.70354222
pos_x = 0.3
pos_y = 23.8
pos_z = 0
pitch = 0
yaw = 0
roll = 0
img_height = 972
img_width = 1296

[[devices]]
name = "Bulb_1"
pin = 23
min_x = -7
min_y = 40
min_z = 100
max_x = -3
max_y = 52
max_z = 110

[[devices]]
name = "Bulb_2"
pin = 27
min_x = -7
min_y = -110
min_z = 95
max_x = -3
max_y = -150
max_z = 100
